### PR TITLE
ensure we are running all tests on travis

### PR DESCRIPTION
**Pull request by jlipps**
supersedes #67

### CODE REVIEW

**Comment by jlipps** [comment]
@imurchie i think i put -r in the wrong place. trying again.

**Comment by imurchie** [comment]
I seem to have steered you wrong... `--recursive` is needed. `-r` is short for `--require`.

https://mochajs.org/#usage

**Comment by jlipps** [comment]
@imurchie do you know how to make travis run again?

**Comment by jlipps** [comment]
aha there is a rerun button. build is going again here: https://travis-ci.org/appium/appium-ios-driver/builds/101941697

**Comment by jlipps** [comment]
build won't run on a force push i guess. closing and reopening.

**Pull request closed without merging**
