### PR TITLE
Pass locale and language to instruments, now that it supports them

### PR DESCRIPTION
**Pull request by crummy**
Pass locale and language to instruments; after https://github.com/appium/appium-instruments/pull/85 is merged it will launch an app with them.

### CODE REVIEW

**Comment by jlipps** [comment]
When this is merged it will address https://github.com/appium/appium/issues/7513

**Comment by imurchie** [comment]
Looks good! Can you check the conflicts in `package.json`, and squash into a single commit? Then we can get this in.

**Comment by crummy** [comment]
Oops, accidentally closed this when squashing the commits. Should be good to go now.

**Comment by imurchie** [comment]
Published in `appium-ios-driver@1.15.2`.

**Comment by lolotoms** [comment]
Hi, did you find something to change locale and language with appium-Xcuitest-driver??

**Comment by crummy** [comment]
I haven't looked into xcuitest; this PR was for instruments only.

**Comment by lolotoms** [comment]
I found this => http://shashikantjagtap.net/ios-localization-internationalization-testing-xcuitest/ I will investigate

**Pull request merged**
