### PR TITLE
Move appium-uiauto into driver

### PR DESCRIPTION
**Pull request by imurchie**
What fun! Another one bites the dust!

### CODE REVIEW

**Comment by imurchie** [comment]
https://github.com/appium/appium/issues/7468

**Comment by imurchie** [comment]
Putting this on the back-burner while working on some other things. Need to figure out flakey tests.

**Comment by jlipps** [comment]
@imurchie any more insight into flakey tests here?

**Comment by imurchie** [comment]
Some recent work I did on stabilizing this driver has made this work!

**Pull request merged**
