### PR TITLE
TravisCI - parellel tests

### PR DESCRIPTION
**Pull request by scottdixon**
- Fixes TravisCI instruments issue.
- Runs TestApp and UICatalog tests side by side, takes ~30 mins total.

@imurchie

### CODE REVIEW

**Comment by scottdixon** [comment]
Testing Travis - please don't merge this.

**Comment by jlipps** [comment]
scott let us know when this is ready for review. for example i wouldn't want the instruments files in the root dir

**Comment by scottdixon** [comment]
I'd also like your thoughts on the best way to run coveralls at the end. There's no 'after_all_success' or similar option, hence the `FINAL_GULP=coveralls`. WWJLD?

**Comment by jlipps** [comment]
that's an interesting strategy. i actually haven't set coveralls up on CI yet so a better person to ask would be @sebv

**Comment by imurchie** [comment]
I'm going to merge this and then fix a few things.

**Pull request merged**
