### PR TITLE
Reset sim deletes simulator and doesnt re-create.

### PR DESCRIPTION
**Pull request by rafael-chavez**

### CODE REVIEW

**Comment by rafael-chavez** [comment]
@sebv do all pull requests require unit tests?

**Comment by imurchie** [comment]
Ideally, yes.

**Comment by rafael-chavez** [comment]
Ok ill add some unit tests thanks for reviewing @imurchie

**Comment by imurchie** [comment]
Seems easier to just clean up the simulator.

https://github.com/appium/appium-ios-driver/pull/85

**Comment by rafael-chavez** [comment]
agreed! Thanks @imurchie

**Comment by imurchie** [comment]
Closing, as the cleaning code is in now.

**Pull request closed without merging**
