### PR TITLE
add remoteDebugProxy to descaps

### PR DESCRIPTION
**Pull request by yfangsl**
All further info regarding this pull request can be found at appium/appium#10960

### CODE REVIEW

**Comment by imurchie** [comment]
Does this not need to be passed into the RemoteDebugger? 

https://github.com/appium/appium-ios-driver/blob/master/lib/commands/context.js#L172-L179

**Comment by imurchie** [comment]
`appium-xcuitest-driver` uses parts of `appium-ios-driver`, and extends its functionality. If the cap is in `appium-ios-driver` then it will be accepted by both, as `appium-xcuitest-driver` pulls all the ios driver's caps and then adds some.

But both drivers implement a version of `getNewRemoteDebugger` because they need different parameters (like the socket path, which the ios driver knows nothing about, and should not know anything about):
* `appium-ios-driver`: https://github.com/appium/appium-ios-driver/blob/master/lib/commands/context.js#L172-L179
* `appium-xcuitest-driver`: https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/context.js#L63-L73

**Comment by ThomasFettSauce** [comment]
Thanks for the clarification!
Then I agree that we pass the capability also here, so that we cover both cases:
https://github.com/appium/appium-ios-driver/blob/master/lib/commands/context.js#L172-L179

**Comment by yfangsl** [comment]
Got it, will add it in today

**Pull request merged**
