### PR TITLE
add capabilities for visual testing of native apps

### PR DESCRIPTION
**Pull request by jlipps**
superseding #253 (cc @danielputerman)

### CODE REVIEW

**Comment by jlipps** [comment]
ok @mykola-mokhnach made your suggested `getScreenHeight` change here

**Comment by jlipps** [comment]
@mykola-mokhnach @imurchie anything else blocking a merge here?

**Comment by mykola-mokhnach** [comment]
LGTM, @imurchie  any comments from your side?

**Comment by jlipps** [comment]
\o/ published in `appium-ios-driver@1.30.0`

**Pull request merged**
