### PR TITLE
add in-built app: Calendar's support.

### PR DESCRIPTION
**Pull request by purplum**
add in-built app support for Calendar.

### CODE REVIEW

**Comment by imurchie** [comment]
Awesome! Thanks for the work in making this happen!

A simple test would be great to have. I've written one that would suffice, if you would like to add it to your PR. The file should be, I think, `test/e2e/driver/built-in-apps-e2e-specs.js` and the contents are here: https://gist.github.com/imurchie/6efbd0bd5a5e228d3b1e2b3dbf7ea8e3

**Comment by purplum** [comment]
@imurchie , just added the e2etest case fetched from the repo you provided.
Thanks!

**Comment by imurchie** [comment]
Whoops! I should have linted that first.

Can you run `gulp jshint` and fix the errors that come up, then re-push?

**Comment by purplum** [comment]
checked the build log, seems it's using ios8.4, so need to change the deviceName from "iPhone 6s" to "iPhone 6".

**Comment by purplum** [comment]
@imurchie Fixed now.

**Comment by imurchie** [comment]
Thanks! Sorry for the test not being completely right.

One final thing: can you squash this into a single commit? Then I can merge.

**Comment by purplum** [comment]
Opened a new PR with squash commit..
Close this one.

**Comment by imurchie** [comment]
Ah! Sorry. For future reference, after you squash you can just force-push to the same branch and it will update here. But I'll track the other PR.

**Pull request closed without merging**
