### PR TITLE
use appium-base-driver instead of express/mjsonwp

### PR DESCRIPTION
**Pull request by jlipps**

### CODE REVIEW

**Comment by jlipps** [comment]
```
 1) testapp - active "before all" hook: callee$1$0:
     TypeError: undefined is not a function
      at startServer$ (test/e2e/setup-base.js:16:18)
      at tryCatch (node_modules/babel-runtime/regenerator/runtime.js:67:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-runtime/regenerator/runtime.js:315:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel-runtime/regenerator/runtime.js:100:21)
      at invoke (node_modules/babel-runtime/regenerator/runtime.js:136:37)
      at enqueueResult (node_modules/babel-runtime/regenerator/runtime.js:185:17)
      at new Promise (node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
      at AsyncIterator.enqueue (node_modules/babel-runtime/regenerator/runtime.js:184:16)
      at AsyncIterator.prototype.(anonymous function) [as next] (node_modules/babel-runtime/regenerator/runtime.js:100:21)
      at Object.runtime.async (node_modules/babel-runtime/regenerator/runtime.js:209:12)
      at startServer (test/e2e/setup-base.js:15:13)
      at callee$1$0$ (test/e2e/setup-base.js:38:13)
      at tryCatch (node_modules/babel-runtime/regenerator/runtime.js:67:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-runtime/regenerator/runtime.js:315:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel-runtime/regenerator/runtime.js:100:21)
      at invoke (node_modules/babel-runtime/regenerator/runtime.js:136:37)
      at enqueueResult (node_modules/babel-runtime/regenerator/runtime.js:185:17)
      at new Promise (node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
      at AsyncIterator.enqueue (node_modules/babel-runtime/regenerator/runtime.js:184:16)
      at AsyncIterator.prototype.(anonymous function) [as next] (node_modules/babel-runtime/regenerator/runtime.js:100:21)
      at Object.runtime.async (node_modules/babel-runtime/regenerator/runtime.js:209:12)
      at Context.callee$1$0 (test/e2e/setup-base.js:36:10)
```

looks like something related to my changes probably

**Comment by jlipps** [comment]
it was `import { baseServer } from 'appium-base-driver'`. now needs to be `import { server as baseServer } from 'appium-base-driver'`

**Comment by jlipps** [comment]
seems like a flake, @imurchie?

```
  1) uicatalog - background app should background the app for 4 of seconds (+/- 6 secs):
     AssertionError: expected '<?xml version="1.0" encoding="UTF-8"?>\n<AppiumAUT>\n    <UIAApplication name="" label="" value="" dom="" enabled="false" valid="false" visible="false" hint="" path="/0" x="0" y="0" width="0" height="0">\n    </UIAApplication>\n</AppiumAUT>' to include 'UICatalog'
      at Suite.callee$1$0$ (test/e2e/uicatalog/background-app-specs.js:15:43)
      at tryCatch (node_modules/babel-runtime/regenerator/runtime.js:67:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-runtime/regenerator/runtime.js:315:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel-runtime/regenerator/runtime.js:100:21)
      at GeneratorFunctionPrototype.invoke (node_modules/babel-runtime/regenerator/runtime.js:136:37)
      at run (node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
      at node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
      at flush (node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
```

the push build passed.

**Comment by imurchie** [comment]
Yup. That is flakey. I think I've made it less so in my UICatalog PR, as it hasn't flaked in a while. But we'll see.

**Comment by jlipps** [comment]
published as 1.12.1

**Pull request merged**
