### PR TITLE
fix: Remove iwd4 to avoid macOS notarization error for AppiumDesktop

### PR DESCRIPTION
**Pull request by KazuCocoa**
Apple requires notarization for macOS 10.15. If the `.app` has binaries which do not work on over 10.9, `The binary uses an SDK older than the 10.9 SDK` error will be raises. (And the app will not work on 10.15)
https://developer.apple.com/news/?id=04102019a

A friend of mine told me `iwd4` binary did not work on 10.9, so `The binary uses an SDK older than the 10.9 SDK` will happen when we try to create a package with notarization for AppiumDesktop. So, we must remove this binary for now (Or remove this binary when creating a desktop app.)

Xcode 4 requires Mac OS X 10.8. Xcode 4 support iOS 6. The market share is low, nowadays.
We also can guide users to use lower Appium versions for such lower Xcode version cases.

Hence, in this PR, I simply removed the binary and put an error message for Xcode 4 environment if the user tried to use it. (Xcode 5 can work on 10.9)

The `iwd4` path is resolved in below code in `instruments/utils.js`
```
async function getIwdPath (xcodeMajorVersion) {
  let thirdpartyPath = path.resolve(rootDir, '..', 'instruments-iwd');
  let iwdPath = path.resolve(thirdpartyPath, `iwd${xcodeMajorVersion}`);
  if (!await fs.exists(iwdPath)) {
    iwdPath = path.resolve(thirdpartyPath, 'iwd');
  }
  log.debug(`Found Insruments-Without-Delay: ${iwdPath}`);
  return iwdPath;
}
```

### CODE REVIEW

**Comment by KazuCocoa** [comment]
mm, other `.dylib` in other directories in `instruments-iwd` also have `The binary is not signed.`

Let me merge this for now. Will take a look further

**Comment by zcmgyu** [comment]
@KazuCocoa Hi, I also got the same "The binary is not signed" error message in the rest `iwd*` of `instruments-iwd`. How could you escape that errors when notarization?


```
{
"severity": "error",
"code": null,
"path": "MATT_Client.zip/MATT Client.app/Contents/Resources/app/node_modules/appium-ios-driver/instruments-iwd/iwd/DTMobileISShim.dylib.dSYM/Contents/Resources/DWARF/DTMobileISShim.dylib",
"message": "The binary is not signed.",
"docUrl": null,
"architecture": "i386"
},
{
"severity": "error",
"code": null,
"path": "XXX.app/Contents/Resources/app/node_modules/appium-ios-driver/instruments-iwd/iwd5/ScriptAgentShim.dylib.dSYM/Contents/Resources/DWARF/ScriptAgentShim.dylib",
"message": "The binary is not signed.",
"docUrl": null,
"architecture": "i386"
},

"severity": "error",
"code": null,
"path": "XXX.app/Contents/Resources/app/node_modules/appium-ios-driver/instruments-iwd/iwd6/DTMobileISShim.dylib.dSYM/Contents/Resources/DWARF/DTMobileISShim.dylib",
"message": "The binary is not signed.",
"docUrl": null,
"architecture": "i386"
},

{
"severity": "error",
"code": null,
"path": "MATT_Client.zip/MATT Client.app/Contents/Resources/app/node_modules/appium-ios-driver/instruments-iwd/iwd7/DTMobileISShim.dylib.dSYM/Contents/Resources/DWARF/DTMobileISShim.dylib",
"message": "The binary is not signed.",
"docUrl": null,
"architecture": "i386"
},
```

**Comment by KazuCocoa** [comment]
Simply, you can remove them sine XCTest automationName does not need them. XCTest driver only supports Xcode 10+.

**Comment by zcmgyu** [comment]
@KazuCocoa Thank for your inform

**Pull request merged**
